include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    no_leading_underscores_for_local_identifiers: false
    library_private_types_in_public_api: false
    use_build_context_synchronously: false
    require_trailing_commas: true
    
analyzer:
  errors:
    invalid_annotation_target: ignore
