name: item_repository
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/Lorenzohidalgo/item_repository

environment:
  sdk: '>=2.18.2 <=3.3.6'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3

dev_dependencies:
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
